# Generated by Django 5.2.1 on 2025-06-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
    ]
