# Generated by Django 5.2.1 on 2025-05-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test_field',
        ),
        migrations.AddField(
            model_name='washingmachine',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
