# Generated by Django 5.2.1 on 2025-05-23 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_remove_user_test_field_washingmachine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='default1234', max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.washingmachine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.user')),
            ],
        ),
    ]
