# Generated by Django 5.2.1 on 2025-05-25 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_user_password_waitlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('machine_type', models.CharField(choices=[('washer', '세탁기'), ('dryer', '건조기')], max_length=10)),
                ('is_in_use', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='laundry.building')),
            ],
            options={
                'unique_together': {('building', 'name', 'machine_type')},
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.machine'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.machine'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_info', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='WashingMachine',
        ),
    ]
